from read_input import read_file
from hierholzer import hierholzer
from is_semi_eulerian_graph import is_semi_eulerian_graph
from is_eulerian_graph import is_eulerian_graph
from is_connected import is_connected